package sdk

import (
	"bytes"
	"embed"
	"fmt"
	"path/filepath"
	"text/template"

	"github.com/nitrictech/nitric/cli/pkg/schema"
	"github.com/spf13/afero"
)

//go:embed python_proto/**/**/*.py
var protoFiles embed.FS

// GeneratePythonSDK generates Python SDK
func GeneratePythonSDK(fs afero.Fs, appSpec schema.Application, outPath string) error {
	tmpl := template.Must(template.New("client").Parse(pythonClientTemplate))
	data := AppSpecToTemplateData(appSpec)

	var buf bytes.Buffer
	err := tmpl.Execute(&buf, data)
	if err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	sdkPath := filepath.Join(outPath, "sdk")

	// Create nitric/proto directory
	protoPath := filepath.Join(outPath, "proto")
	err = fs.MkdirAll(protoPath, 0755)
	if err != nil {
		return fmt.Errorf("failed to create proto directory: %w", err)
	}

	// Copy proto files
	err = copyProtoFiles(fs, protoPath)
	if err != nil {
		return fmt.Errorf("failed to copy proto files: %w", err)
	}

	storagePath := filepath.Join(sdkPath, "storage")

	err = fs.MkdirAll(storagePath, 0755)
	if err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	init_files := []string{
		filepath.Join(outPath, "__init__.py"),
		filepath.Join(sdkPath, "__init__.py"),
	}

	for _, filePath := range init_files {
		if err := afero.WriteFile(fs, filePath, []byte(""), 0644); err != nil {
			return fmt.Errorf("failed to write init file: %w", err)
		}
	}

	if err := afero.WriteFile(fs, filepath.Join(storagePath, "__init__.py"), buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write bucket file: %w", err)
	}

	fmt.Printf("Python SDK generated at %s\n", outPath)

	return nil
}

const pythonClientTemplate = `# Code generated by Nitric SDK generator. DO NOT EDIT.

import atexit
import re
import os

from urllib.parse import urlparse
from grpclib.client import Channel
from google.protobuf import duration_pb2

from nitric.proto.storage.v2 import StorageReadRequest, StorageWriteRequest, StorageDeleteRequest, StorageListBlobsRequest, StorageExistsRequest, StoragePreSignUrlRequest, StorageStub


def format_url(url: str):
    """Add the default http scheme prefix to urls without one."""
    if not re.match("^((?:http|ftp|https):)?//", url.lower()):
        return "http://{0}".format(url)
    return url


class ChannelManager:
	"""A singleton class to manage the gRPC channel."""

	SERVICE_ADDRESS = os.environ.get("SERVICE_ADDRESS", "127.0.0.1:50051")

	channel = None

	@classmethod
	def get_channel(cls) -> Channel:
		"""Return the channel instance."""

		if cls.channel is None:
			cls._create_channel()
		return cls.channel  # type: ignore

	@classmethod
	def _create_channel(cls):
		"""Create a new channel instance."""

		channel_url = urlparse(format_url(cls.SERVICE_ADDRESS))
		cls.channel = Channel(host=channel_url.hostname, port=channel_url.port)
		atexit.register(cls._close_channel)

	@classmethod
	def _close_channel(cls):
		"""Close the channel instance."""

		if cls.channel is not None:
			cls.channel.close()
			cls.channel = None


class Bucket:
	def __init__(self, bucket_name):
		self.__storage_client = StorageStub(ChannelManager.get_channel())
		self.bucket_name = bucket_name

	async def read(self, file):
		"""Read a file from the bucket"""
		request = StorageReadRequest(
			bucket_name=self.bucket_name,
			key=file
		)
		response = await self.__storage_client.read(request)
		return response.body

	async def write(self, file, data):
		"""Write a file to the bucket"""
		request = StorageWriteRequest(
			bucket_name=self.bucket_name,
			key=file,
			body=data
		)
		await self.__storage_client.write(request)

	async def delete(self, file):
		"""Delete a file from the bucket"""
		request = StorageDeleteRequest(
			bucket_name=self.bucket_name,
			key=file
		)
		await self.__storage_client.delete(request)

	async def list(self, prefix=""):
		"""List files in the bucket with optional prefix"""
		request = StorageListBlobsRequest(
			bucket_name=self.bucket_name,
			prefix=prefix
		)
		response = await self.__storage_client.list_blobs(request)
		return [blob.key for blob in response.blobs]

	async def exists(self, file):
		"""Check if a file exists in the bucket"""
		request = StorageExistsRequest(
			bucket_name=self.bucket_name,
			key=file
		)
		response = await self.__storage_client.exists(request)
		return response.exists

	async def get_download_url(self, file, expiry_seconds=300):
		"""Get a pre-signed URL for downloading a file"""
		request = StoragePreSignUrlRequest(
			bucket_name=self.bucket_name,
			key=file,
			operation=StoragePreSignUrlRequest.READ,
			expiry=duration_pb2.Duration(seconds=expiry_seconds)
		)
		response = await self.__storage_client.pre_sign_url(request)
		return response.url

	async def get_upload_url(self, file, expiry_seconds=300):
		"""Get a pre-signed URL for uploading a file"""
		request = StoragePreSignUrlRequest(
			bucket_name=self.bucket_name,
			key=file,
			operation=StoragePreSignUrlRequest.WRITE,
			expiry=duration_pb2.Duration(seconds=expiry_seconds)
		)
		response = await self.__storage_client.pre_sign_url(request)
		return response.url

{{range .Buckets}}
{{.Name}} = Bucket("{{.Name}}")
{{end}}`

// copyProtoFiles recursivelycopies proto files from embedded filesystem to output directory
func copyProtoFiles(fs afero.Fs, outPath string) error {
	return walkEmbeddedFS(protoFiles, "python_proto", func(path string, isDir bool) error {
		// Skip the root directory
		if path == "python_proto" {
			return nil
		}

		// Get relative path without python_proto prefix
		targetPath := filepath.Join(outPath, path[len("python_proto/"):])

		if isDir {
			return fs.MkdirAll(targetPath, 0755)
		}

		// Read file from embedded filesystem
		data, err := protoFiles.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read proto file %s: %w", path, err)
		}

		// Write file to output directory
		if err := afero.WriteFile(fs, targetPath, data, 0644); err != nil {
			return fmt.Errorf("failed to write proto file %s: %w", targetPath, err)
		}

		return nil
	})
}

// walkEmbeddedFS walks through the embedded filesystem and calls the copyFile for each file
func walkEmbeddedFS(fs embed.FS, root string, copyFile func(path string, isDir bool) error) error {
	entries, err := fs.ReadDir(root)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		path := filepath.Join(root, entry.Name())
		if entry.IsDir() {
			if err := copyFile(path, true); err != nil {
				return err
			}

			if err := walkEmbeddedFS(fs, path, copyFile); err != nil {
				return err
			}
		} else {
			if err := copyFile(path, false); err != nil {
				return err
			}
		}
	}

	return nil
}
